# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - main

pr:
  - main
  
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build   
        condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
        steps:
        - script: |
            npm install &&
            mv -f ./src/env.production.json ./src/env.json
            npm run build && 
            cp -R ./build ../Backend/TableTop/App
          workingDirectory: Frontend
          name: 'Build_Frontend'
          displayName: 'Build Frontend'
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'
          workingDirectory: Backend
  - stage: Deploy
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: Production_Build_And_Deploy   
        steps:
        - script: |
            npm install &&
            mv -f ./src/env.production.json ./src/env.json
            npm run build && 
            cp -R ./build ../Backend/TableTop/App
          workingDirectory: Frontend
          name: 'Build_Frontend'
          displayName: 'Build Frontend'
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'
          workingDirectory: Backend
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'Azure subscription 1(135449c3-e7ed-4552-b603-b20a35f29f53)'
            appType: 'webAppLinux'
            appName: 'table-top-map'
            package: '$(System.DefaultWorkingDirectory)/**/*.zip'
            runtimeStack: 'DOTNETCORE|6.0'
          
